{
 "title": "Cassandra Dashboard by ORAMAD",
 "description": "https://github.com/Sarma1807/Prometheus-Grafana-Cassandra",
 "tags": [ "Apache Cassandra" ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "3m",
 "templating": {
  "list": [
   {
    "name": "cluster",
    "label": "cluster",
    "query": {
     "query": "label_values(oramad_system_info, cass_cluster_name)"
    }
   },
   {
    "name": "data_center",
    "label": "data_center",
    "query": {
     "query": "label_values(oramad_system_info{cass_cluster_name=~\"$cluster\"}, data_center)"
    }
   },
   {
    "name": "hostname",
    "label": "hostname",
    "query": {
     "query": "label_values(oramad_system_info{cass_cluster_name=~\"$cluster\",data_center=~\"$data_center\"}, hostname_short)"
    }
   },
   {
    "name": "keyspace",
    "label": "keyspace",
    "query": {
     "query": "label_values(oramad_table_size_bytes{cass_cluster_name=~\"$cluster\", data_center=~\"$data_center\", hostname_short=~\"$hostname\"}, keyspace_name)"
    }
   },
   {
    "name": "table",
    "label": "table",
    "query": {
     "query": "label_values(oramad_table_size_bytes{cass_cluster_name=~\"$cluster\", data_center=~\"$data_center\", hostname_short=~\"$hostname\", keyspace_name=~\"$keyspace\"}, table_name)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "$cluster : System Summary",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "repeat": "cluster",
   "collapsed": true,
   "panels": [
    {
     "type": "text",
     "gridPos": { "h": 2, "w": 3, "x": 0, "y": 1 },
     "options": {
      "content": "<h2> <center> Server </center> </h2>"
     }
    },
    {
     "type": "text",
     "gridPos": { "h": 2, "w": 3, "x": 3, "y": 1 },
     "options": {
      "content": "<h2> <center> Domain </center> </h2>"
     }
    },
    {
     "type": "text",
     "gridPos": { "h": 2, "w": 2, "x": 6, "y": 1 },
     "options": {
      "content": "<h2> <center> IP </center> </h2>"
     }
    },
    {
     "type": "text",
     "gridPos": { "h": 2, "w": 3, "x": 8, "y": 1 },
     "options": {
      "content": "<h2> <center> Uptime </center> </h2>"
     }
    },
    {
     "type": "text",
     "gridPos": { "h": 2, "w": 6, "x": 11, "y": 1 },
     "options": {
      "content": "<h2> <center> OS </center> </h2>"
     }
    },
    {
     "type": "text",
     "gridPos": { "h": 2, "w": 3, "x": 17, "y": 1 },
     "options": {
      "content": "<h2> <center> RAM Usage </center> </h2>"
     }
    },
    {
     "type": "text",
     "gridPos": { "h": 2, "w": 3, "x": 20, "y": 1 },
     "options": {
      "content": "<h2> <center> CPU Usage </center> </h2>"
     }
    },
    {
     "type": "stat",
     "gridPos": { "h": 2, "w": 3, "x": 0, "y": 3 },
     "repeat": "hostname",
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "oramad_system_info{hostname_short=~\"$hostname\"}",
       "legendFormat": "{{hostname_short}}"
      }
     ]
    },
    {
     "type": "stat",
     "gridPos": { "h": 2, "w": 3, "x": 3, "y": 3 },
     "repeat": "hostname",
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "oramad_system_info{hostname_short=~\"$hostname\"}",
       "legendFormat": "{{domainname}}"
      }
     ]
    },
    {
     "type": "stat",
     "gridPos": { "h": 2, "w": 2, "x": 6, "y": 3 },
     "repeat": "hostname",
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "oramad_system_info{hostname_short=~\"$hostname\"}",
       "legendFormat": "{{hostname_ip}}"
      }
     ]
    },
    {
     "type": "stat",
     "gridPos": { "h": 2, "w": 3, "x": 8, "y": 3 },
     "repeat": "hostname",
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "oramad_system_info{hostname_short=~\"$hostname\"}",
       "legendFormat": "{{uptime_pretty_short}}"
      }
     ]
    },
    {
     "type": "stat",
     "gridPos": { "h": 2, "w": 6, "x": 11, "y": 3 },
     "repeat": "hostname",
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "oramad_system_info{hostname_short=~\"$hostname\"}",
       "legendFormat": "{{os_release}}"
      }
     ]
    },
    {
     "type": "stat",
     "gridPos": { "h": 2, "w": 3, "x": 17, "y": 3 },
     "repeat": "hostname",
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "oramad_ram_used_percent{hostname_short=~\"$hostname\"}",
       "legendFormat": "{{hostname_short}}"
      }
     ]
    },
    {
     "type": "stat",
     "gridPos": { "h": 2, "w": 3, "x": 20, "y": 3 },
     "repeat": "hostname",
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "oramad_cpu_used_percent{hostname_short=~\"$hostname\"}",
       "legendFormat": "{{hostname_short}}"
      }
     ]
    },
    {
     "type": "stat",
     "gridPos": { "h": 2, "w": 3, "x": 0, "y": 5 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "oramad_system_info{hostname_short=~\"$hostname\"}",
       "legendFormat": "{{hostname_short}}"
      }
     ]
    },
    {
     "type": "stat",
     "gridPos": { "h": 2, "w": 3, "x": 3, "y": 5 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "oramad_system_info{hostname_short=~\"$hostname\"}",
       "legendFormat": "{{domainname}}"
      }
     ]
    },
    {
     "type": "stat",
     "gridPos": { "h": 2, "w": 2, "x": 6, "y": 5 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "oramad_system_info{hostname_short=~\"$hostname\"}",
       "legendFormat": "{{hostname_ip}}"
      }
     ]
    },
    {
     "type": "stat",
     "gridPos": { "h": 2, "w": 3, "x": 8, "y": 5 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "oramad_system_info{hostname_short=~\"$hostname\"}",
       "legendFormat": "{{uptime_pretty_short}}"
      }
     ]
    },
    {
     "type": "stat",
     "gridPos": { "h": 2, "w": 6, "x": 11, "y": 5 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "oramad_system_info{hostname_short=~\"$hostname\"}",
       "legendFormat": "{{os_release}}"
      }
     ]
    },
    {
     "type": "stat",
     "gridPos": { "h": 2, "w": 3, "x": 17, "y": 5 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "oramad_ram_used_percent{hostname_short=~\"$hostname\"}",
       "legendFormat": "{{hostname_short}}"
      }
     ]
    },
    {
     "type": "stat",
     "gridPos": { "h": 2, "w": 3, "x": 20, "y": 5 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "oramad_cpu_used_percent{hostname_short=~\"$hostname\"}",
       "legendFormat": "{{hostname_short}}"
      }
     ]
    },
    {
     "type": "stat",
     "gridPos": { "h": 2, "w": 3, "x": 0, "y": 7 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "oramad_system_info{hostname_short=~\"$hostname\"}",
       "legendFormat": "{{hostname_short}}"
      }
     ]
    },
    {
     "type": "stat",
     "gridPos": { "h": 2, "w": 3, "x": 3, "y": 7 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "oramad_system_info{hostname_short=~\"$hostname\"}",
       "legendFormat": "{{domainname}}"
      }
     ]
    },
    {
     "type": "stat",
     "gridPos": { "h": 2, "w": 2, "x": 6, "y": 7 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "oramad_system_info{hostname_short=~\"$hostname\"}",
       "legendFormat": "{{hostname_ip}}"
      }
     ]
    },
    {
     "type": "stat",
     "gridPos": { "h": 2, "w": 3, "x": 8, "y": 7 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "oramad_system_info{hostname_short=~\"$hostname\"}",
       "legendFormat": "{{uptime_pretty_short}}"
      }
     ]
    },
    {
     "type": "stat",
     "gridPos": { "h": 2, "w": 6, "x": 11, "y": 7 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "oramad_system_info{hostname_short=~\"$hostname\"}",
       "legendFormat": "{{os_release}}"
      }
     ]
    },
    {
     "type": "stat",
     "gridPos": { "h": 2, "w": 3, "x": 17, "y": 7 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "oramad_ram_used_percent{hostname_short=~\"$hostname\"}",
       "legendFormat": "{{hostname_short}}"
      }
     ]
    },
    {
     "type": "stat",
     "gridPos": { "h": 2, "w": 3, "x": 20, "y": 7 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "oramad_cpu_used_percent{hostname_short=~\"$hostname\"}",
       "legendFormat": "{{hostname_short}}"
      }
     ]
    }
   ]
  },
  {
   "title": "$cluster : System Storage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "repeat": "cluster",
   "collapsed": true,
   "panels": [
    {
     "title": "$hostname : Mount Points Used %",
     "type": "bargauge",
     "gridPos": { "h": 5, "w": 8, "x": 0, "y": 2 },
     "repeat": "hostname",
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "oramad_mount_used_percent{hostname_short=~\"$hostname\"}",
       "legendFormat": "{{mountpoint}}"
      }
     ]
    },
    {
     "title": "$hostname : Mount Points Used %",
     "type": "bargauge",
     "gridPos": { "h": 5, "w": 8, "x": 8, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "oramad_mount_used_percent{hostname_short=~\"$hostname\"}",
       "legendFormat": "{{mountpoint}}"
      }
     ]
    },
    {
     "title": "$hostname : Mount Points Used %",
     "type": "bargauge",
     "gridPos": { "h": 5, "w": 8, "x": 16, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "oramad_mount_used_percent{hostname_short=~\"$hostname\"}",
       "legendFormat": "{{mountpoint}}"
      }
     ]
    },
    {
     "title": "$hostname : inodes Used %",
     "type": "gauge",
     "gridPos": { "h": 5, "w": 8, "x": 0, "y": 7 },
     "repeat": "hostname",
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "oramad_mount_used_inodes_percent{hostname_short=~\"$hostname\"}",
       "legendFormat": "{{mountpoint}}"
      }
     ]
    },
    {
     "title": "$hostname : inodes Used %",
     "type": "gauge",
     "gridPos": { "h": 5, "w": 8, "x": 8, "y": 7 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "oramad_mount_used_inodes_percent{hostname_short=~\"$hostname\"}",
       "legendFormat": "{{mountpoint}}"
      }
     ]
    },
    {
     "title": "$hostname : inodes Used %",
     "type": "gauge",
     "gridPos": { "h": 5, "w": 8, "x": 16, "y": 7 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "oramad_mount_used_inodes_percent{hostname_short=~\"$hostname\"}",
       "legendFormat": "{{mountpoint}}"
      }
     ]
    }
   ]
  },
  {
   "title": "$cluster : System CPU/RAM Usage Graphs",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "repeat": "cluster",
   "collapsed": true,
   "panels": [
    {
     "title": "CPU Usage %",
     "type": "graph",
     "gridPos": { "h": 11, "w": 11, "x": 0, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "oramad_cpu_used_percent{hostname_short=~\"$hostname\"}",
       "legendFormat": "{{hostname_short}}"
      }
     ]
    },
    {
     "title": "RAM Usage",
     "type": "graph",
     "gridPos": { "h": 11, "w": 11, "x": 11, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "oramad_ram_used_bytes{hostname_short=~\"$hostname\"}",
       "legendFormat": "{{hostname_short}} Used"
      }
     ]
    }
   ]
  },
  {
   "title": "$cluster : Cassandra Nodes",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "repeat": "cluster",
   "collapsed": true,
   "panels": [
    {
     "title": "Total Nodes",
     "type": "stat",
     "gridPos": { "h": 4, "w": 3, "x": 0, "y": 4 },
     "options": { "reduceOptions": { "calcs": [ "max" ] } },
     "targets": [
      {
       "expr": "max by (cluster) (oramad_cass_nodes_count{cass_cluster_name=~\"$cluster\"})",
       "legendFormat": "Nodes"
      }
     ]
    },
    {
     "title": "Nodes Up",
     "type": "stat",
     "gridPos": { "h": 4, "w": 3, "x": 3, "y": 4 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(oramad_cass_up{cass_cluster_name=~\"$cluster\"})",
       "legendFormat": "Up"
      }
     ]
    },
    {
     "title": "Nodes Down",
     "type": "stat",
     "gridPos": { "h": 4, "w": 3, "x": 6, "y": 4 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "(max by (cluster) (oramad_cass_nodes_count{cass_cluster_name=~\"$cluster\"})) - sum(oramad_cass_up{cass_cluster_name=~\"$cluster\"})",
       "legendFormat": "Down"
      }
     ]
    },
    {
     "title": "Total Data Centers",
     "type": "stat",
     "gridPos": { "h": 4, "w": 3, "x": 9, "y": 4 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "max by (cluster) (oramad_cass_datacenters_count{cass_cluster_name=~\"$cluster\"})",
       "legendFormat": "DCs"
      }
     ]
    },
    {
     "title": "Nodes Per Data Center",
     "type": "stat",
     "gridPos": { "h": 4, "w": 5, "x": 12, "y": 4 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "count by (data_center) (oramad_system_info{cass_cluster_name=\"$cluster\"})",
       "legendFormat": "{{data_center}}"
      }
     ]
    },
    {
     "type": "text",
     "gridPos": { "h": 2, "w": 17, "x": 0, "y": 8 },
     "options": {
      "content": "<center>\r\n<br>\r\n<h5 style=\"background-color:dark-gray;\">\r\nIf Node Counts Are Wrong, Then Make Sure Agent Is Configured On Each Cassandra Node & All Agents Are Running.\r\n</h5> \r\n</center>"
     }
    }
   ]
  },
  {
   "title": "$cluster : Cassandra Summary",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "repeat": "cluster",
   "collapsed": true,
   "panels": [
    {
     "type": "text",
     "gridPos": { "h": 2, "w": 2, "x": 0, "y": 5 },
     "options": {
      "content": "<h3> <center> Node </center> </h3>"
     }
    },
    {
     "type": "text",
     "gridPos": { "h": 2, "w": 2, "x": 2, "y": 5 },
     "options": {
      "content": "<h3> <center> Version </center> </h3>"
     }
    },
    {
     "type": "text",
     "gridPos": { "h": 2, "w": 2, "x": 4, "y": 5 },
     "options": {
      "content": "<h3> <center> DC </center> </h3>"
     }
    },
    {
     "type": "text",
     "gridPos": { "h": 2, "w": 2, "x": 6, "y": 5 },
     "options": {
      "content": "<h3> <center> Rack </center> </h3>"
     }
    },
    {
     "type": "text",
     "gridPos": { "h": 2, "w": 2, "x": 8, "y": 5 },
     "options": {
      "content": "<h3> <center> Tokens </center> </h3>"
     }
    },
    {
     "type": "text",
     "gridPos": { "h": 2, "w": 2, "x": 10, "y": 5 },
     "options": {
      "content": "<h3> <center> Uptime </center> </h3>"
     }
    },
    {
     "type": "text",
     "gridPos": { "h": 2, "w": 3, "x": 12, "y": 5 },
     "options": {
      "content": "<h3> <center> Data Size </center> </h3>"
     }
    },
    {
     "type": "text",
     "gridPos": { "h": 2, "w": 3, "x": 15, "y": 5 },
     "options": {
      "content": "<h3> <center> Data Repair % </center> </h3>"
     }
    },
    {
     "type": "stat",
     "gridPos": { "h": 2, "w": 2, "x": 0, "y": 7 },
     "repeat": "hostname",
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "oramad_cass_up{hostname_short=~\"$hostname\"}",
       "legendFormat": "{{hostname_short}}"
      }
     ]
    },
    {
     "type": "stat",
     "gridPos": { "h": 2, "w": 2, "x": 2, "y": 7 },
     "repeat": "hostname",
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "oramad_cass_node_info{hostname_short=~\"$hostname\"}",
       "legendFormat": "{{cass_version}}"
      }
     ]
    },
    {
     "type": "stat",
     "gridPos": { "h": 2, "w": 2, "x": 4, "y": 7 },
     "repeat": "hostname",
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "oramad_cass_node_info{hostname_short=~\"$hostname\"}",
       "legendFormat": "{{data_center}}"
      }
     ]
    },
    {
     "type": "stat",
     "gridPos": { "h": 2, "w": 2, "x": 6, "y": 7 },
     "repeat": "hostname",
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "oramad_cass_node_info{hostname_short=~\"$hostname\"}",
       "legendFormat": "{{node_rack}}"
      }
     ]
    },
    {
     "type": "stat",
     "gridPos": { "h": 2, "w": 2, "x": 8, "y": 7 },
     "repeat": "hostname",
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "oramad_cass_node_info{hostname_short=~\"$hostname\"}",
       "legendFormat": "{{num_tokens}}"
      }
     ]
    },
    {
     "type": "stat",
     "gridPos": { "h": 2, "w": 2, "x": 10, "y": 7 },
     "repeat": "hostname",
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "oramad_cass_node_info{hostname_short=~\"$hostname\"}",
       "legendFormat": "{{cass_uptime_pretty}}"
      }
     ]
    },
    {
     "type": "stat",
     "gridPos": { "h": 2, "w": 3, "x": 12, "y": 7 },
     "repeat": "hostname",
     "fieldConfig": { "defaults": { "unit": "decmbytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "oramad_cass_node_info{hostname_short=~\"$hostname\"}",
       "legendFormat": "{{data_size}}"
      }
     ]
    },
    {
     "type": "stat",
     "gridPos": { "h": 2, "w": 3, "x": 15, "y": 7 },
     "repeat": "hostname",
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "oramad_cass_node_info{hostname_short=~\"$hostname\"}",
       "legendFormat": "{{node_repair_percent}}"
      }
     ]
    },
    {
     "type": "stat",
     "gridPos": { "h": 2, "w": 2, "x": 0, "y": 9 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "oramad_cass_up{hostname_short=~\"$hostname\"}",
       "legendFormat": "{{hostname_short}}"
      }
     ]
    },
    {
     "type": "stat",
     "gridPos": { "h": 2, "w": 2, "x": 2, "y": 9 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "oramad_cass_node_info{hostname_short=~\"$hostname\"}",
       "legendFormat": "{{cass_version}}"
      }
     ]
    },
    {
     "type": "stat",
     "gridPos": { "h": 2, "w": 2, "x": 4, "y": 9 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "oramad_cass_node_info{hostname_short=~\"$hostname\"}",
       "legendFormat": "{{data_center}}"
      }
     ]
    },
    {
     "type": "stat",
     "gridPos": { "h": 2, "w": 2, "x": 6, "y": 9 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "oramad_cass_node_info{hostname_short=~\"$hostname\"}",
       "legendFormat": "{{node_rack}}"
      }
     ]
    },
    {
     "type": "stat",
     "gridPos": { "h": 2, "w": 2, "x": 8, "y": 9 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "oramad_cass_node_info{hostname_short=~\"$hostname\"}",
       "legendFormat": "{{num_tokens}}"
      }
     ]
    },
    {
     "type": "stat",
     "gridPos": { "h": 2, "w": 2, "x": 10, "y": 9 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "oramad_cass_node_info{hostname_short=~\"$hostname\"}",
       "legendFormat": "{{cass_uptime_pretty}}"
      }
     ]
    },
    {
     "type": "stat",
     "gridPos": { "h": 2, "w": 3, "x": 12, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "decmbytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "oramad_cass_node_info{hostname_short=~\"$hostname\"}",
       "legendFormat": "{{data_size}}"
      }
     ]
    },
    {
     "type": "stat",
     "gridPos": { "h": 2, "w": 3, "x": 15, "y": 9 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "oramad_cass_node_info{hostname_short=~\"$hostname\"}",
       "legendFormat": "{{node_repair_percent}}"
      }
     ]
    },
    {
     "type": "stat",
     "gridPos": { "h": 2, "w": 2, "x": 0, "y": 11 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "oramad_cass_up{hostname_short=~\"$hostname\"}",
       "legendFormat": "{{hostname_short}}"
      }
     ]
    },
    {
     "type": "stat",
     "gridPos": { "h": 2, "w": 2, "x": 2, "y": 11 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "oramad_cass_node_info{hostname_short=~\"$hostname\"}",
       "legendFormat": "{{cass_version}}"
      }
     ]
    },
    {
     "type": "stat",
     "gridPos": { "h": 2, "w": 2, "x": 4, "y": 11 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "oramad_cass_node_info{hostname_short=~\"$hostname\"}",
       "legendFormat": "{{data_center}}"
      }
     ]
    },
    {
     "type": "stat",
     "gridPos": { "h": 2, "w": 2, "x": 6, "y": 11 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "oramad_cass_node_info{hostname_short=~\"$hostname\"}",
       "legendFormat": "{{node_rack}}"
      }
     ]
    },
    {
     "type": "stat",
     "gridPos": { "h": 2, "w": 2, "x": 8, "y": 11 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "oramad_cass_node_info{hostname_short=~\"$hostname\"}",
       "legendFormat": "{{num_tokens}}"
      }
     ]
    },
    {
     "type": "stat",
     "gridPos": { "h": 2, "w": 2, "x": 10, "y": 11 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "oramad_cass_node_info{hostname_short=~\"$hostname\"}",
       "legendFormat": "{{cass_uptime_pretty}}"
      }
     ]
    },
    {
     "type": "stat",
     "gridPos": { "h": 2, "w": 3, "x": 12, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "decmbytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "oramad_cass_node_info{hostname_short=~\"$hostname\"}",
       "legendFormat": "{{data_size}}"
      }
     ]
    },
    {
     "type": "stat",
     "gridPos": { "h": 2, "w": 3, "x": 15, "y": 11 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "oramad_cass_node_info{hostname_short=~\"$hostname\"}",
       "legendFormat": "{{node_repair_percent}}"
      }
     ]
    },
    {
     "type": "text",
     "gridPos": { "h": 2, "w": 14, "x": 0, "y": 13 },
     "options": {
      "content": "<center>\r\n<h5 style=\"background-color:green;\"> Node Color Green Indicates Cassandra Is Up and Running Normally </h5> \r\n<h5 style=\"background-color:red;\"> Node Color Red Indicates Cassandra Is Down </h5> \r\n</center>"
     }
    }
   ]
  },
  {
   "title": "$cluster : Cassandra Memory",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 },
   "repeat": "cluster",
   "collapsed": true,
   "panels": [
    {
     "title": "Heap Used %",
     "type": "graph",
     "gridPos": { "h": 10, "w": 18, "x": 0, "y": 6 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "oramad_cass_heap_used_percent{hostname_short=~\"$hostname\"}",
       "legendFormat": "{{hostname_short}}"
      }
     ]
    },
    {
     "type": "text",
     "gridPos": { "h": 2, "w": 2, "x": 0, "y": 16 },
     "options": {
      "content": "<h3> <center> Node </center> </h3>"
     }
    },
    {
     "type": "text",
     "gridPos": { "h": 2, "w": 4, "x": 2, "y": 16 },
     "options": {
      "content": "<h3> <center> Heap Allocated </center> </h3>"
     }
    },
    {
     "type": "text",
     "gridPos": { "h": 2, "w": 4, "x": 6, "y": 16 },
     "options": {
      "content": "<h3> <center> Heap Used </center> </h3>"
     }
    },
    {
     "type": "text",
     "gridPos": { "h": 2, "w": 4, "x": 10, "y": 16 },
     "options": {
      "content": "<h3> <center> Heap Used % </center> </h3>"
     }
    },
    {
     "type": "text",
     "gridPos": { "h": 2, "w": 4, "x": 14, "y": 16 },
     "options": {
      "content": "<h3> <center> Off Heap Used </center> </h3>"
     }
    },
    {
     "type": "stat",
     "gridPos": { "h": 2, "w": 2, "x": 0, "y": 18 },
     "repeat": "hostname",
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "oramad_cass_up{hostname_short=~\"$hostname\"}",
       "legendFormat": "{{hostname_short}}"
      }
     ]
    },
    {
     "type": "stat",
     "gridPos": { "h": 2, "w": 4, "x": 2, "y": 18 },
     "repeat": "hostname",
     "fieldConfig": { "defaults": { "unit": "decmbytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "oramad_cass_heap_total_mb{hostname_short=~\"$hostname\"}",
       "legendFormat": "{{hostname_short}}"
      }
     ]
    },
    {
     "type": "stat",
     "gridPos": { "h": 2, "w": 4, "x": 6, "y": 18 },
     "repeat": "hostname",
     "fieldConfig": { "defaults": { "unit": "decmbytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "oramad_cass_heap_used_mb{hostname_short=~\"$hostname\"}",
       "legendFormat": "{{hostname_short}}"
      }
     ]
    },
    {
     "type": "stat",
     "gridPos": { "h": 2, "w": 4, "x": 10, "y": 18 },
     "repeat": "hostname",
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "oramad_cass_heap_used_percent{hostname_short=~\"$hostname\"}",
       "legendFormat": "{{hostname_short}}"
      }
     ]
    },
    {
     "type": "stat",
     "gridPos": { "h": 2, "w": 4, "x": 14, "y": 18 },
     "repeat": "hostname",
     "fieldConfig": { "defaults": { "unit": "decmbytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "oramad_cass_off_heap_used_mb{hostname_short=~\"$hostname\"}",
       "legendFormat": "{{hostname_short}}"
      }
     ]
    },
    {
     "type": "stat",
     "gridPos": { "h": 2, "w": 2, "x": 0, "y": 20 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "oramad_cass_up{hostname_short=~\"$hostname\"}",
       "legendFormat": "{{hostname_short}}"
      }
     ]
    },
    {
     "type": "stat",
     "gridPos": { "h": 2, "w": 4, "x": 2, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "decmbytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "oramad_cass_heap_total_mb{hostname_short=~\"$hostname\"}",
       "legendFormat": "{{hostname_short}}"
      }
     ]
    },
    {
     "type": "stat",
     "gridPos": { "h": 2, "w": 4, "x": 6, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "decmbytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "oramad_cass_heap_used_mb{hostname_short=~\"$hostname\"}",
       "legendFormat": "{{hostname_short}}"
      }
     ]
    },
    {
     "type": "stat",
     "gridPos": { "h": 2, "w": 4, "x": 10, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "oramad_cass_heap_used_percent{hostname_short=~\"$hostname\"}",
       "legendFormat": "{{hostname_short}}"
      }
     ]
    },
    {
     "type": "stat",
     "gridPos": { "h": 2, "w": 4, "x": 14, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "decmbytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "oramad_cass_off_heap_used_mb{hostname_short=~\"$hostname\"}",
       "legendFormat": "{{hostname_short}}"
      }
     ]
    },
    {
     "type": "stat",
     "gridPos": { "h": 2, "w": 2, "x": 0, "y": 22 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "oramad_cass_up{hostname_short=~\"$hostname\"}",
       "legendFormat": "{{hostname_short}}"
      }
     ]
    },
    {
     "type": "stat",
     "gridPos": { "h": 2, "w": 4, "x": 2, "y": 22 },
     "fieldConfig": { "defaults": { "unit": "decmbytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "oramad_cass_heap_total_mb{hostname_short=~\"$hostname\"}",
       "legendFormat": "{{hostname_short}}"
      }
     ]
    },
    {
     "type": "stat",
     "gridPos": { "h": 2, "w": 4, "x": 6, "y": 22 },
     "fieldConfig": { "defaults": { "unit": "decmbytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "oramad_cass_heap_used_mb{hostname_short=~\"$hostname\"}",
       "legendFormat": "{{hostname_short}}"
      }
     ]
    },
    {
     "type": "stat",
     "gridPos": { "h": 2, "w": 4, "x": 10, "y": 22 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "oramad_cass_heap_used_percent{hostname_short=~\"$hostname\"}",
       "legendFormat": "{{hostname_short}}"
      }
     ]
    },
    {
     "type": "stat",
     "gridPos": { "h": 2, "w": 4, "x": 14, "y": 22 },
     "fieldConfig": { "defaults": { "unit": "decmbytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "oramad_cass_off_heap_used_mb{hostname_short=~\"$hostname\"}",
       "legendFormat": "{{hostname_short}}"
      }
     ]
    }
   ]
  },
  {
   "title": "$cluster : Cassandra Query Language",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 },
   "repeat": "cluster",
   "collapsed": true,
   "panels": [
    { "type": "text", "gridPos": { "h": 2, "w": 2, "x": 0, "y": 7 }, "options": { "content": "<h3> <center>  </center> </h3>" } },
    {
     "type": "text",
     "gridPos": { "h": 2, "w": 8, "x": 2, "y": 7 },
     "options": {
      "content": "<h3> <center> Prepared CQL Statements </center> </h3>"
     }
    },
    {
     "type": "text",
     "gridPos": { "h": 2, "w": 6, "x": 10, "y": 7 },
     "options": {
      "content": "<h3> <center> Unprepared CQL Statements </center> </h3>"
     }
    },
    {
     "type": "text",
     "gridPos": { "h": 2, "w": 6, "x": 16, "y": 7 },
     "options": {
      "content": "<h3> <center> Prepared vs. Unprepared CQL Statements </center> </h3>"
     }
    },
    {
     "type": "text",
     "gridPos": { "h": 2, "w": 2, "x": 0, "y": 9 },
     "options": {
      "content": "<h3> <center> Node </center> </h3>"
     }
    },
    {
     "type": "text",
     "gridPos": { "h": 2, "w": 3, "x": 2, "y": 9 },
     "options": {
      "content": "<h3> <center> Cached # </center> </h3>"
     }
    },
    {
     "type": "text",
     "gridPos": { "h": 2, "w": 5, "x": 5, "y": 9 },
     "options": {
      "content": "<h3> <center> Executed # </center> </h3>"
     }
    },
    {
     "type": "text",
     "gridPos": { "h": 2, "w": 6, "x": 10, "y": 9 },
     "options": {
      "content": "<h3> <center> Executed # </center> </h3>"
     }
    },
    {
     "type": "text",
     "gridPos": { "h": 2, "w": 3, "x": 16, "y": 9 },
     "options": {
      "content": "<h3> <center> Prepared % </center> </h3>"
     }
    },
    {
     "type": "text",
     "gridPos": { "h": 2, "w": 3, "x": 19, "y": 9 },
     "options": {
      "content": "<h3> <center> Unprepared % </center> </h3>"
     }
    },
    {
     "type": "stat",
     "gridPos": { "h": 2, "w": 2, "x": 0, "y": 11 },
     "repeat": "hostname",
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "oramad_cass_up{hostname_short=~\"$hostname\"}",
       "legendFormat": "{{hostname_short}}"
      }
     ]
    },
    {
     "type": "stat",
     "gridPos": { "h": 2, "w": 3, "x": 2, "y": 11 },
     "repeat": "hostname",
     "fieldConfig": { "defaults": { "unit": "locale" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "oramad_cql_prep_stmts_cached{hostname_short=~\"$hostname\"}",
       "legendFormat": "{{hostname_short}}"
      }
     ]
    },
    {
     "type": "stat",
     "gridPos": { "h": 2, "w": 5, "x": 5, "y": 11 },
     "repeat": "hostname",
     "fieldConfig": { "defaults": { "unit": "locale" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "oramad_cql_prep_stmts_executed{hostname_short=~\"$hostname\"}",
       "legendFormat": "{{hostname_short}}"
      }
     ]
    },
    {
     "type": "stat",
     "gridPos": { "h": 2, "w": 6, "x": 10, "y": 11 },
     "repeat": "hostname",
     "fieldConfig": { "defaults": { "unit": "locale" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "oramad_cql_unprep_stmts_executed{hostname_short=~\"$hostname\"}",
       "legendFormat": "{{hostname_short}}"
      }
     ]
    },
    {
     "type": "stat",
     "gridPos": { "h": 2, "w": 3, "x": 16, "y": 11 },
     "repeat": "hostname",
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "(oramad_cql_prep_stmts_executed{hostname_short=~\"$hostname\"} * 100) / (oramad_cql_prep_stmts_executed{hostname_short=~\"$hostname\"} + oramad_cql_unprep_stmts_executed{hostname_short=~\"$hostname\"})",
       "legendFormat": "{{hostname_short}}"
      }
     ]
    },
    {
     "type": "stat",
     "gridPos": { "h": 2, "w": 3, "x": 19, "y": 11 },
     "repeat": "hostname",
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "(oramad_cql_unprep_stmts_executed{hostname_short=~\"$hostname\"} * 100) / (oramad_cql_prep_stmts_executed{hostname_short=~\"$hostname\"} + oramad_cql_unprep_stmts_executed{hostname_short=~\"$hostname\"})",
       "legendFormat": "{{hostname_short}}"
      }
     ]
    },
    {
     "type": "stat",
     "gridPos": { "h": 2, "w": 2, "x": 0, "y": 13 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "oramad_cass_up{hostname_short=~\"$hostname\"}",
       "legendFormat": "{{hostname_short}}"
      }
     ]
    },
    {
     "type": "stat",
     "gridPos": { "h": 2, "w": 3, "x": 2, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "locale" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "oramad_cql_prep_stmts_cached{hostname_short=~\"$hostname\"}",
       "legendFormat": "{{hostname_short}}"
      }
     ]
    },
    {
     "type": "stat",
     "gridPos": { "h": 2, "w": 5, "x": 5, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "locale" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "oramad_cql_prep_stmts_executed{hostname_short=~\"$hostname\"}",
       "legendFormat": "{{hostname_short}}"
      }
     ]
    },
    {
     "type": "stat",
     "gridPos": { "h": 2, "w": 6, "x": 10, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "locale" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "oramad_cql_unprep_stmts_executed{hostname_short=~\"$hostname\"}",
       "legendFormat": "{{hostname_short}}"
      }
     ]
    },
    {
     "type": "stat",
     "gridPos": { "h": 2, "w": 3, "x": 16, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "(oramad_cql_prep_stmts_executed{hostname_short=~\"$hostname\"} * 100) / (oramad_cql_prep_stmts_executed{hostname_short=~\"$hostname\"} + oramad_cql_unprep_stmts_executed{hostname_short=~\"$hostname\"})",
       "legendFormat": "{{hostname_short}}"
      }
     ]
    },
    {
     "type": "stat",
     "gridPos": { "h": 2, "w": 3, "x": 19, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "(oramad_cql_unprep_stmts_executed{hostname_short=~\"$hostname\"} * 100) / (oramad_cql_prep_stmts_executed{hostname_short=~\"$hostname\"} + oramad_cql_unprep_stmts_executed{hostname_short=~\"$hostname\"})",
       "legendFormat": "{{hostname_short}}"
      }
     ]
    },
    {
     "type": "stat",
     "gridPos": { "h": 2, "w": 2, "x": 0, "y": 15 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "oramad_cass_up{hostname_short=~\"$hostname\"}",
       "legendFormat": "{{hostname_short}}"
      }
     ]
    },
    {
     "type": "stat",
     "gridPos": { "h": 2, "w": 3, "x": 2, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "locale" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "oramad_cql_prep_stmts_cached{hostname_short=~\"$hostname\"}",
       "legendFormat": "{{hostname_short}}"
      }
     ]
    },
    {
     "type": "stat",
     "gridPos": { "h": 2, "w": 5, "x": 5, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "locale" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "oramad_cql_prep_stmts_executed{hostname_short=~\"$hostname\"}",
       "legendFormat": "{{hostname_short}}"
      }
     ]
    },
    {
     "type": "stat",
     "gridPos": { "h": 2, "w": 6, "x": 10, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "locale" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "oramad_cql_unprep_stmts_executed{hostname_short=~\"$hostname\"}",
       "legendFormat": "{{hostname_short}}"
      }
     ]
    },
    {
     "type": "stat",
     "gridPos": { "h": 2, "w": 3, "x": 16, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "(oramad_cql_prep_stmts_executed{hostname_short=~\"$hostname\"} * 100) / (oramad_cql_prep_stmts_executed{hostname_short=~\"$hostname\"} + oramad_cql_unprep_stmts_executed{hostname_short=~\"$hostname\"})",
       "legendFormat": "{{hostname_short}}"
      }
     ]
    },
    {
     "type": "stat",
     "gridPos": { "h": 2, "w": 3, "x": 19, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "(oramad_cql_unprep_stmts_executed{hostname_short=~\"$hostname\"} * 100) / (oramad_cql_prep_stmts_executed{hostname_short=~\"$hostname\"} + oramad_cql_unprep_stmts_executed{hostname_short=~\"$hostname\"})",
       "legendFormat": "{{hostname_short}}"
      }
     ]
    },
    {
     "type": "text",
     "gridPos": { "h": 2, "w": 14, "x": 2, "y": 17 },
     "options": {
      "content": "<center>\r\n<h5 style=\"background-color:#0055FF;\"> Metrics Are Reset During Restart Of Cassandra </h5> \r\n</center>"
     }
    }
   ]
  },
  {
   "title": "$cluster : Cassandra Commit Logs",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 },
   "repeat": "cluster",
   "collapsed": true,
   "panels": [
    {
     "type": "text",
     "gridPos": { "h": 2, "w": 2, "x": 0, "y": 8 },
     "options": {
      "content": "<h3> <center> Node </center> </h3>"
     }
    },
    {
     "type": "text",
     "gridPos": { "h": 2, "w": 5, "x": 2, "y": 8 },
     "options": {
      "content": "<h3> <center> Pending Tasks </center> </h3>"
     }
    },
    {
     "type": "text",
     "gridPos": { "h": 2, "w": 5, "x": 7, "y": 8 },
     "options": {
      "content": "<h3> <center> Completed Tasks </center> </h3>"
     }
    },
    {
     "type": "text",
     "gridPos": { "h": 2, "w": 5, "x": 12, "y": 8 },
     "options": {
      "content": "<h3> <center> Size On Disk </center> </h3>"
     }
    },
    {
     "type": "stat",
     "gridPos": { "h": 2, "w": 2, "x": 0, "y": 10 },
     "repeat": "hostname",
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "oramad_cass_up{hostname_short=~\"$hostname\"}",
       "legendFormat": "{{hostname_short}}"
      }
     ]
    },
    {
     "type": "stat",
     "gridPos": { "h": 2, "w": 5, "x": 2, "y": 10 },
     "repeat": "hostname",
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "oramad_commitlog_pending_tasks{hostname_short=~\"$hostname\"}",
       "legendFormat": "{{hostname_short}}"
      }
     ]
    },
    {
     "type": "stat",
     "gridPos": { "h": 2, "w": 5, "x": 7, "y": 10 },
     "repeat": "hostname",
     "fieldConfig": { "defaults": { "unit": "locale" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "oramad_commitlog_completed_tasks{hostname_short=~\"$hostname\"}",
       "legendFormat": "{{hostname_short}}"
      }
     ]
    },
    {
     "type": "stat",
     "gridPos": { "h": 2, "w": 5, "x": 12, "y": 10 },
     "repeat": "hostname",
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "oramad_commitlog_size_bytes{hostname_short=~\"$hostname\"}",
       "legendFormat": "{{hostname_short}}"
      }
     ]
    },
    {
     "type": "stat",
     "gridPos": { "h": 2, "w": 2, "x": 0, "y": 12 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "oramad_cass_up{hostname_short=~\"$hostname\"}",
       "legendFormat": "{{hostname_short}}"
      }
     ]
    },
    {
     "type": "stat",
     "gridPos": { "h": 2, "w": 5, "x": 2, "y": 12 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "oramad_commitlog_pending_tasks{hostname_short=~\"$hostname\"}",
       "legendFormat": "{{hostname_short}}"
      }
     ]
    },
    {
     "type": "stat",
     "gridPos": { "h": 2, "w": 5, "x": 7, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "locale" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "oramad_commitlog_completed_tasks{hostname_short=~\"$hostname\"}",
       "legendFormat": "{{hostname_short}}"
      }
     ]
    },
    {
     "type": "stat",
     "gridPos": { "h": 2, "w": 5, "x": 12, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "oramad_commitlog_size_bytes{hostname_short=~\"$hostname\"}",
       "legendFormat": "{{hostname_short}}"
      }
     ]
    },
    {
     "type": "stat",
     "gridPos": { "h": 2, "w": 2, "x": 0, "y": 14 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "oramad_cass_up{hostname_short=~\"$hostname\"}",
       "legendFormat": "{{hostname_short}}"
      }
     ]
    },
    {
     "type": "stat",
     "gridPos": { "h": 2, "w": 5, "x": 2, "y": 14 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "oramad_commitlog_pending_tasks{hostname_short=~\"$hostname\"}",
       "legendFormat": "{{hostname_short}}"
      }
     ]
    },
    {
     "type": "stat",
     "gridPos": { "h": 2, "w": 5, "x": 7, "y": 14 },
     "fieldConfig": { "defaults": { "unit": "locale" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "oramad_commitlog_completed_tasks{hostname_short=~\"$hostname\"}",
       "legendFormat": "{{hostname_short}}"
      }
     ]
    },
    {
     "type": "stat",
     "gridPos": { "h": 2, "w": 5, "x": 12, "y": 14 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "oramad_commitlog_size_bytes{hostname_short=~\"$hostname\"}",
       "legendFormat": "{{hostname_short}}"
      }
     ]
    }
   ]
  },
  {
   "title": "$cluster : Cassandra Keyspaces (Excluding System Keyspaces)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "repeat": "cluster",
   "collapsed": true,
   "panels": [
    {
     "type": "table",
     "gridPos": { "h": 12, "w": 11, "x": 0, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "oramad_keyspace_size_bytes{hostname_short=~\"$hostname\", keyspace_name=~\"$keyspace\"}",
       "legendFormat": "{{hostname_short}}"
      }
     ]
    },
    {
     "title": "Keyspace Size Changes",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 11, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "oramad_keyspace_size_bytes{hostname_short=~\"$hostname\", keyspace_name=~\"$keyspace\"}",
       "legendFormat": "{{hostname_short}} : {{keyspace_name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "$cluster : Cassandra Tables (Excluding System Tables)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "repeat": "cluster",
   "collapsed": true,
   "panels": [
    {
     "type": "table",
     "gridPos": { "h": 11, "w": 11, "x": 0, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "oramad_table_size_bytes{hostname_short=~\"$hostname\", keyspace_name=~\"$keyspace\", table_name=~\"$table\"}",
       "legendFormat": "{{hostname_short}}"
      }
     ]
    },
    {
     "title": "Keyspace Size Changes",
     "type": "graph",
     "gridPos": { "h": 11, "w": 12, "x": 11, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "oramad_table_size_bytes{hostname_short=~\"$hostname\", keyspace_name=~\"$keyspace\", table_name=~\"$table\"}",
       "legendFormat": "{{hostname_short}} : {{keyspace_name}}.{{table_name}}"
      }
     ]
    }
   ]
  },
  { "title": "Author Information", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "type": "text",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 11 },
   "options": {
    "content": "<h2> Cassandra Dashboard by ORAMAD </h2>\r\n<br>\r\n<h5>\r\nSoftware Used : <br>\r\nPrometheus : Collects and Stores Metrics in Time Series Database <br>\r\nPrometheus node_exporter : Gathers and Publishes Metrics From Each Server <br>\r\nGrafana : Visualization Tool for Metrics Served by Prometheus <br>\r\nMetrics : OS and Cassandra Metrics Are Gathered Using Light-weight Custom Bash Scripts and Cassandra metrics-reporter <br>\r\n</h5>\r\n<h6> Version 1.2 (March 2021)</h6>\r\n<br>\r\n<h4> <a href=\"https://github.com/sarma1807/Prometheus-Grafana-Cassandra\" target=\"_blank\">Visit GitHub Page For More Details</a> </h4>\r\n"
   }
  }
 ]
}